apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-logrotate
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/managed-by: Helm
data:
  logrotate.conf: |-
{{ tpl .Values.logrotate.conf . | indent 4 }}
